---
engines:
  eslint:
    enabled: true
    config:
      config: config/eslint.json
  tslint:
    enabled: true
    channel: beta
    config: config/tslint.json
ratings:
  paths:
  - "src/**.js"
  - "cli/**.js"
  - "lib/aspromise/**.js"
  - "lib/base64/**.js"
  - "lib/eventemitter/**.js"
  - "lib/fetch/**.js"
  - "lib/float/**.js"
  - "lib/inquire/**.js"
  - "lib/path/**.js"
  - "lib/pool/**.js"
  - "lib/utf8/**.js"
  - "ext/**.js"
  - "**/*.d.ts"
exclude_paths:
  - "dist/**"
  - "**/tests/**"
  - "cli/wrappers/**"
