ui: tape
browsers:
  - name: chrome
    version: [26, latest]
  - name: firefox
    version: [4, latest]
  - name: microsoftedge
    version: [13, latest]
  - name: safari
    version: [5, latest]
  - name: ie
    version: [9, 10, 11]
  - name: opera
    version: [11, 12]
  - name: android
    version: [4.4, 5.0, latest]
  - name: iphone
    version: [8.1, 9.0, latest]
scripts:
  - lib/polyfill.js
  - node_modules/long/dist/long.js
tunnel:
  type: ngrok
  proto: tcp
browserify:
  - external: long
  - require: ./lib/tape-adapter
    expose: intimidate
    entry: true
