// Generated by running the following from the root folder of this project:
// ./bin/proto2js tests/extend2.proto -commonjs=sample > tests/extend2.js
// then changed the require value, and added this comment.

module.exports = require("../ProtoBuf.js").newBuilder().import({
    "package": "sample.basepackage",
    "messages": [
        {
            "name": "Foo",
            "fields": [
                {
                    "rule": "optional",
                    "type": "string",
                    "name": "blah",
                    "id": 1,
                    "options": {}
                }
            ],
            "enums": [],
            "messages": [],
            "options": {}
        }
    ],
    "enums": [],
    "imports": [],
    "options": {},
    "extends": [],
    "services": []
}).import({
    "package": "sample.mypackage",
    "messages": [
        {
            "name": "Person",
            "fields": [
                {
                    "rule": "required",
                    "type": "string",
                    "name": "name",
                    "id": 1,
                    "options": {}
                },
                {
                    "rule": "required",
                    "type": "int32",
                    "name": "id",
                    "id": 2,
                    "options": {}
                },
                {
                    "rule": "optional",
                    "type": "string",
                    "name": "email",
                    "id": 3,
                    "options": {}
                }
            ],
            "enums": [],
            "messages": [],
            "options": {}
        }
    ],
    "enums": [],
    "imports": [],
    "options": {},
    "extends": [
        {
            "messageToExtend": "sample.basepackage.Foo",
            "fields": [
                {
                    "rule": "optional",
                    "type": "int32",
                    "name": "bar",
                    "id": 1001,
                    "options": {}
                }
            ]
        },
        {
            "messageToExtend": "sample.basepackage.Foo",
            "fields": [
                {
                    "rule": "optional",
                    "type": "sample.mypackage.Person",
                    "name": "person",
                    "id": 1002,
                    "options": {}
                },
                {
                    "rule": "optional",
                    "type": "Person",
                    "name": "anotherPerson",
                    "id": 1003,
                    "options": {}
                }
            ]
        }
    ],
    "services": []
}).build("sample");
