name: "Test"
on:
  push:
    branches:
    - master
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]
env:
  MIN_NODE_VERSION: &min_node_version "12"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: "lts/*"
    - name: "Install dependencies"
      run: npm install
    - name: "Lint sources"
      run: npm run lint:sources -- --max-warnings 0
    - name: "Lint types"
      run: npm run lint:types
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [*min_node_version, "lts/*"]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node_version }}
    - name: "Install dependencies"
      run: npm install
    - name: "Test sources"
      run: npm run test:sources
    - name: "Test types"
      run: npm run test:types
  bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: "lts/*"
    - name: "Install dependencies"
      run: npm install
    - name: "Run benchmark"
      run: npm run bench
